
const char* VERTEX =
    "#version 100\n"
    "attribute vec3 vertexPosition;\n"
    "attribute vec2 vertexTexCoord;\n"
    "attribute vec4 vertexColor;\n"
    "uniform mat4 mvp;\n"
    "varying vec2 fragTexCoord;\n"
    "varying vec4 fragColor;\n"
    "void main()\n"
    "{\n"
    "    fragTexCoord = vertexTexCoord;\n"
    "    fragColor = vertexColor;\n"
    "    gl_Position = mvp * vec4(vertexPosition, 1.0);\n"
    "}";

const char* FRAGMENT = 
    "#version 100\n"
    "precision mediump float;\n"
    "varying vec2 fragTexCoord;\n"
    "varying vec4 fragColor;\n"
    "uniform sampler2D texture0;\n"
    "uniform vec4 colDiffuse;\n"
    "uniform vec2 resolution;\n"
    "uniform float time;\n"
    "void main() {\n"
    "    // curves \n"
    "    vec2 p = fragTexCoord * 2.0 - 1.0;\n"
    "    p *= 1.0 + 0.035 * dot(p, p);\n"
    "    vec2 uv = p * 0.5 + 0.5;\n"
    "    if (uv.x < 0.0 || uv.x > 1.0 || uv.y < 0.0 || uv.y > 1.0) {\n"
    "        gl_FragColor = vec4(0.0, 0.0, 0.0, 1.0);\n"
    "        return;\n"
    "    }\n"
    "    // scanlines\n"
    "    float scan_phase = time * 0.5;\n"
    "    vec3 color = texture2D(texture0, uv).rgb;\n"
    "    float scan = sin(uv.y * resolution.y * 1.5 + scan_phase);\n"
    "    color *= 0.90 + 0.05* scan;\n"
    "    // vignette\n"
    "    vec2 v = uv * (1.0 - uv.yx);\n"
    "    float vig = pow(clamp(v.x * v.y * 18.0, 0.0, 1.0), 0.18);\n"
    "    color *= vig;\n"
    "    gl_FragColor = vec4(color, 1.0);\n"
    "}";
